### PR TITLE
Add fastlane

### PR DESCRIPTION
**Pull request by s1204IT**
https://github.com/iamr0s/Dhizuku/issues/11#issuecomment-1575470026

---
And, Upgrade gradle.

### CODE REVIEW

**Comment by s1204IT** [comment]
@iamr0s 
Could you please merge this?
Without this, We can't use Dhizuku's features in Aurora Store.

**Comment by s1204IT** [comment]
@theimpulson
I'm not familiar with F-Droid at all, but will this change satisfy the requirements?

**Comment by theimpulson** [comment]
@s1204IT while this is a recommendation, the actual requirement of the app to be on F-droid involves adding it to the metadata repo [here](https://gitlab.com/fdroid/fdroiddata) or opening an issue for maintainers to do it for you [here](https://gitlab.com/fdroid/rfp/-/issues)

- Example: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14510

**Comment by iamr0s** [comment]
OK I'm sorry that I was busy with many things, so I didn't notice the pr email.

**Pull request merged**
